
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ouragendaclient.MessageExchanger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marvin
 */
public class JLogin extends javax.swing.JFrame {

    /**
     * Creates new form telaLogin
     */
    public JLogin() {
        MessageExchanger me = new MessageExchanger(10000);
        initComponents();
    }
    
    String userName;
    String userPsswd;
    String message;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        senha = new javax.swing.JPasswordField();
        user = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(830, 530));
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ourA.jpg"))); // NOI18N
        jPanel3.add(jLabel1);

        jTabbedPane1.addTab("Início", jPanel3);

        jPanel2.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel2.setLayout(null);

        senha.setText("senha");
        jPanel2.add(senha);
        senha.setBounds(330, 300, 200, 20);

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel2.add(user);
        user.setBounds(330, 230, 200, 20);

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setText("Entrar");
        login.setToolTipText("");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel2.add(login);
        login.setBounds(320, 380, 140, 23);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ourL.jpg"))); // NOI18N
        bg.setName("Login"); // NOI18N
        jPanel2.add(bg);
        bg.setBounds(10, -40, 810, 550);

        jTabbedPane1.addTab("Login", jPanel2);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 840, 510));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 830, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_userActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
      
    }//GEN-LAST:event_loginActionPerformed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
        
        userName = user.getText();
        userPsswd = new String (senha.getPassword());
        message = "LOGIN&-u="+userName+"&-p="+userPsswd+"";
        MessageExchanger me = new MessageExchanger(10000);
        me.SendMessage(message);
        
        String messageAnswer;
        int i=0;
        
        do
        {
            messageAnswer = me.getMessage();
            System.out.print("");
        }while(messageAnswer.isEmpty());
        
        if(!messageAnswer.equals("LOGIN_FB&-status=FAIL")){
            JFrame jframe = new JFrame();
            JOptionPane.showMessageDialog(jframe,"Login realizado com sucesso.");
            String[] section = messageAnswer.split("&");
            String userId = section[2].substring(8);
            JAgenda jagenda = new JAgenda(userName,userId);
            
            jagenda.setVisible(true);
            dispose();
        }else{
            JFrame jframe = new JFrame();
            JOptionPane.showMessageDialog(jframe,"Login sem sucesso.");
        }
    }//GEN-LAST:event_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JLogin().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables

    private void print(String userName) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
